version: "3.9"

services:
  app:
    build:
      context: .
    container_name: node_backend
    ports:
      - "5000:5000" # ✅ Match backend's port
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Anshu@123#!
      - DB_NAME=vue_with_node
      - DB_PORT=3306
      - APP_PORT=5000
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules 
    command: >
      sh -c "
      npm install &&
      echo '⏳ Waiting for MySQL...' &&
      until nc -z db 3306; do sleep 2; done &&
      echo '✅ MySQL is up! Starting Node in watch mode...' &&
      npm run watch
      "

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Anshu@123#!
      MYSQL_DATABASE: vue_with_node
    ports:
      - "3307:3306" # ✅ 3307 for TablePlus
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:











































